import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/_components/Footer/Footer";
import Navbar from "@/_components/Navbar/Navbar";
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <ToastContainer theme="dark" />
        </div>{" "}
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
